#!/bin/bash 

if docker --version &> /dev/null; then
    echo "Docker is already installed."
else
    echo "Installing docker ...."
    curl -s https://raw.githubusercontent.com/jaintpharsha/install/main/docker | sudo bash 
fi
docker pull sonatype/nexus3:latest
echo "Create volumes for sonarqube to persist data"
docker volume create --name sonatype-work

docker run -d --name nexus \
    -p 8081:8081 \
    -v sonatype-work:/nexus-data \
    sonatype/nexus3


